name: app
description: A new Flutter project.
 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
 
dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.15.0
  firebase_auth: ^3.3.16
  internet_connection_checker: ^0.0.1+4
  get_it: ^7.2.0
  # Bloc for state management
  flutter_bloc: ^8.1.1
  # Value equality
  equatable: ^2.0.5
  # Functional programming thingies
  dartz: ^0.10.1
  # Remote API
  # connectivity: ^0.4.3+7
  http: ^0.13.4
  # Local cache
  shared_preferences: ^2.0.15
  # copertino icons
  cupertino_icons: ^1.0.5 
  dots_indicator: ^2.0.0 
  intl_phone_number_input: ^0.7.0+2
  dio: ^4.0.6
  dio_smart_retry: ^1.0.0
  flutter_native_splash: ^2.2.8
  webview_flutter: ^3.0.4
  # flutter_animated_button: ^2.0.1
  flutter_neumorphic: ^3.0.3
  json_annotation: any
  firebase_database: ^9.1.3
  shimmer: ^2.0.0
  dismissible_page: ^0.7.3
  modal_bottom_sheet: ^2.1.0
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.1.5 
  social_share: ^2.2.1
  cached_network_image: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0 
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.10.0
  build_runner: any
  json_serializable: any

  flutter_lints: ^2.0.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/app.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/img/app.png"
    background_color: "#f4f4f4"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/img/app.png"



flutter_native_splash:
  color: "#fafafa"
  color_dark: "#fafafa"
  image: assets/img/app_avatar.png
  image_dark: assets/img/app_avatar.png
  android_gravity: center
  os_content_mode: center
  fullscreen: true
  android_12:
    image: assets/img/app_avatar_android_12.png
    image_dark: assets/img/app_avatar_android_12.png
    color: "#fafafa"
    color_dark: "#fafafa"

flutter:
 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/html/
    - assets/fixtures/

  fonts:
    - family: VEXA
      fonts:
        - asset: fonts/VEXA.ttf
        - asset: fonts/VEXA ITALIC.ttf
          style: italic
    - family: VEXA_LIGHT
      fonts:
        - asset: fonts/VEXA light.ttf
        - asset: fonts/VEXA light italic.ttf
          style: italic        
    - family: VEXA_THIN
      fonts:
        - asset: fonts/VEXA thin.ttf
        - asset: fonts/VEXA thin italic.ttf       
          style: italic
